name = "zc-wx-server"
main = "src/index.ts"
compatibility_date = "2024-02-01"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "zhanchen_menye_secret_key_2026"
WX_APP_ID = "wx012162a3e0fe4288"         # 微信小程序 AppID (微信公众平台获取)
WX_APP_SECRET = "9087e85db61a697b6a3b2ef7a9906d25" # 微信小程序 AppSecret (微信公众平台获取)

[[d1_databases]]
binding = "DB"
database_name = "zc-db"
database_id = "local-zc-d1-id"
