name = "zc-wx-form"
main = "src/index.ts"
compatibility_date = "2024-02-01"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "zhanchen_menye_secret_key_2026"
WX_APP_ID = "wx012162a3e0fe4288"
WX_APP_SECRET = "9087e85db61a697b6a3b2ef7a9906d25"

[[d1_databases]]
binding = "DB"
database_name = "zc-db"
database_id = "fa0ee2ed-2492-402e-bb27-98e7f4a8e7b3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "zc-oss"
